/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alivecor_neuralsuite_NeuralSuite */

#ifndef _Included_com_alivecor_neuralsuite_NeuralSuite
#define _Included_com_alivecor_neuralsuite_NeuralSuite
#ifdef __cplusplus
extern "C" {
#endif
#undef com_alivecor_neuralsuite_NeuralSuite_debug
#define com_alivecor_neuralsuite_NeuralSuite_debug 1L
#undef com_alivecor_neuralsuite_NeuralSuite_STATUS_SUCCESS
#define com_alivecor_neuralsuite_NeuralSuite_STATUS_SUCCESS 0L
#undef com_alivecor_neuralsuite_NeuralSuite_STATUS_FAILED_SESSION
#define com_alivecor_neuralsuite_NeuralSuite_STATUS_FAILED_SESSION -1L
#undef com_alivecor_neuralsuite_NeuralSuite_STATUS_FAILED_READ_GRAPH
#define com_alivecor_neuralsuite_NeuralSuite_STATUS_FAILED_READ_GRAPH -2L
#undef com_alivecor_neuralsuite_NeuralSuite_STATUS_FAILED_RUN
#define com_alivecor_neuralsuite_NeuralSuite_STATUS_FAILED_RUN -3L
#undef com_alivecor_neuralsuite_NeuralSuite_STATUS_INVALID_INPUT
#define com_alivecor_neuralsuite_NeuralSuite_STATUS_INVALID_INPUT -4L
/*
 * Class:     com_alivecor_neuralsuite_NeuralSuite
 * Method:    jniCheck
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alivecor_neuralsuite_NeuralSuite_jniCheck
  (JNIEnv *, jclass);

/*
 * Class:     com_alivecor_neuralsuite_NeuralSuite
 * Method:    runInversionCheck
 * Signature: ([FFLjava/lang/String;Lcom/alivecor/neuralsuite/NeuralSuite/InversionResult;)I
 */
JNIEXPORT jint JNICALL Java_com_alivecor_neuralsuite_NeuralSuite_runInversionCheck
  (JNIEnv *, jclass, jfloatArray, jfloat, jstring, jobject);

/*
 * Class:     com_alivecor_neuralsuite_NeuralSuite
 * Method:    runIdentityCheck
 * Signature: ([FFLjava/lang/String;Lcom/alivecor/neuralsuite/NeuralSuite/IdentityResult;)I
 */
JNIEXPORT jint JNICALL Java_com_alivecor_neuralsuite_NeuralSuite_runIdentityCheck
  (JNIEnv *, jclass, jfloatArray, jfloat, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
